{% set data= load_setup_py_data() %}
package:
  name: ts-m2gui
  version: {{ data.get('version') }}

source:
  path: ../

build:
  noarch: generic
  script: {{ PYTHON }} -m pip install --no-deps --ignore-installed .
  entry_points:
    - run_m2gui = lsst.ts.m2gui.application:run_application

requirements:
  host:
    - python {{ python }}
    - pip
    - setuptools_scm
    - setuptools
  build:
    - python {{ python }}
    - setuptools_scm
    - setuptools
    - ts-conda-build =0.3
  run:
    - python {{ python }}
    - setuptools
    - setuptools_scm
    - ts-salobj {{ salobj_version }}
    - ts-idl {{ idl_version }}
    - ts-simactuators
    - pandas
    - ts-tcpip
    - ts-utils
    - ts-m2com
